.TH "JUDO" "3" "Feb 18th 2025" "Judo 1.0.0-rc2"
.SH NAME
judo_element \- semantic element
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.B enum judo_element {
.RS
.B JUDO_INVALID,
.B JUDO_NULL,
.B JUDO_TRUE,
.B JUDO_FALSE,
.B JUDO_NUMBER,
.B JUDO_STRING,
.B JUDO_ARRAY_PUSH,
.B JUDO_ARRAY_POP,
.B JUDO_OBJECT_PUSH,
.B JUDO_OBJECT_POP,
.B JUDO_OBJECT_NAME,
.B JUDO_EOF,
.RE
.B };
.fi
.SH DESCRIPTION
This enumeration represents a semantically important element within the JSON stream.
.SH CONSTANTS
.TP
.BR JUDO_INVALID
This element will be returned if an error occurred during the scanning of the JSON stream.
.TP
.BR JUDO_NULL
Represents the JSON \f[C]null\f[R] literal.
.TP
.BR JUDO_TRUE
Represents the JSON boolean \f[C]true\f[R] literal.
.TP
.BR JUDO_FALSE
Represents the JSON boolean \f[C]false\f[R] literal.
.TP
.BR JUDO_NUMBER
Represents a JSON numeric literal.
The floating point representation can be retrieved with \f[B]judo_numberify\f[R](3).
.TP
.BR JUDO_STRING
Represents a JSON string literal.
The decoded string can be retrieved with \f[B]judo_stringify\f[R](3).
.TP
.BR JUDO_ARRAY_PUSH
Indicates an array is about to be parsed.
.TP
.BR JUDO_ARRAY_POP
Indicates an array has finished being parsed.
.TP
.BR JUDO_OBJECT_PUSH
Indicates an object is about to be parsed.
.TP
.BR JUDO_OBJECT_POP
Indicates an object has finished being parsed.
.TP
.BR JUDO_OBJECT_NAME
Represents an object’s member name.
In JavaScript terminology, this would be called the object’s “key.” In JSON5 this might be an ECMAScript 5.1 identifier.
.TP
.BR JUDO_EOF
Represents the end of the JSON stream.
Receiving this element indicates the JSON stream has been successfully fully parsed.
.SH SEE ALSO
.BR judo_numberify (3),
.BR judo_stringify (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .