.TH "JUDO" "3" "Feb 18th 2025" "Judo 1.0.0-rc2"
.SH NAME
judo_error
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.B struct judo_error {
.RS
.B struct judo_span where;
.B char description[JUDO_ERRMAX];
.RE
.B };
.fi
.SH DESCRIPTION
This structure will be populated with error information if \f[B]judo_parse\f[R](3) fails.
.PP
The \f[I]description\f[R] field will be populated with a UTF-8 encoded error message written in US English.
The \f[I]where\f[R] field will be populated with the span of code units where the error was detected in the JSON source text.
You can use the span of code units to derive line and column numbers for more detailed error reporting.
.SH SEE ALSO
.BR judo_parse (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .