.TH "JUDO" "3" "Mar 2nd 2025" "Judo 1.0.0-rc2"
.SH NAME
judo_number \- floating-point storage type
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.BI "typedef long double judo_number;"
.fi
.SH DESCRIPTION
This can be defined as a \f[C]float\f[R], \f[C]double\f[R], or \f[C]long double\f[R] at configuration time.
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .