.TH "JUDO" "3" "Sep 22nd 2025" "Judo 1.1.0"
.SH NAME
judo_value2span \- value lexeme
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.BI "struct judo_span judo_value2span(const judo_value *" value ");"
.fi
.SH DESCRIPTION
The \f[B]judo_value2span\f[R](3) function returns the lexeme of \f[I]value\f[R] in the JSON source text as a span of UTF-8 code units.
.SH RETURN VALUE
Code unit range of the lexeme.
.SH SEE ALSO
.BR judo_value (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .