.TH "JUDO" "3" "Mar 2nd 2025" "Judo 1.0.0-rc3"
.SH NAME
judo_value \- JSON value
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.BI "typedef struct judo_value judo_value;"
.fi
.SH DESCRIPTION
This is an opaque type that represents a JSON value.
See \f[B]judo_type\f[R](3) for all possible types.
.SH SEE ALSO
.BR judo_type (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .