.TH "JUDO" "3" "Sep 22nd 2025" "Judo 1.1.0"
.SH NAME
judo_membfirst \- first object member
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.BI "judo_member *judo_membfirst(judo_value *" value ");"
.fi
.SH DESCRIPTION
The \f[B]judo_membfirst\f[R](3) function retrieves the first member of \f[I]value\f[R], which must be an object.
If \f[I]value\f[R] is NULL, not an object, or is an empty object, then NULL is returned.
.PP
Check if \f[I]value\f[R] is an object with \f[B]judo_gettype\f[R](3) and non-empty with \f[B]judo_len\f[R](3).
.SH RETURN VALUE
The first member of \f[I]value\f[R] or NULL if \f[I]value\f[R] is NULL, not an object, or an empty object.
.SH SEE ALSO
.BR judo_gettype (3),
.BR judo_len (3),
.BR judo_value (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .