.TH "JUDO" "3" "Jul 31st 2025" "Judo 1.0.0"
.SH NAME
judo_stream
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.B struct judo_stream {
.RS
.B struct judo_span where;
.B enum judo_token token;
.B char error[JUDO_ERRMAX];
.RE
.B };
.fi
.SH DESCRIPTION
The structure encompasses the entire state of the Judo scanner.
Instances of this structure can be copied with \f[B]memcpy\f[R](3) to preserve an earlier state.
.PP
The fields \f[I]where\f[R] field refers to the lexeme of the semantic token referenced by \f[I]token\f[R] in the source text, in UTF-8 code units.
If an error occurs, then they refer to the span of code units of the erroneous source text.
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .