.TH "JUDO" "3" "Sep 22nd 2025" "Judo 1.1.0"
.SH NAME
judo_member \- object member
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.BI "typedef struct judo_member judo_member;"
.fi
.SH DESCRIPTION
This is an opaque type that represents an object member, which is a name/value pair.
You can access the name part with \f[B]judo_name2span\f[R](3) and value part with \f[B]judo_membvalue\f[R](3).
.SH SEE ALSO
.BR judo_name2span (3),
.BR judo_membvalue (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .