.TH "JUDO" "3" "Jul 31st 2025" "Judo 1.0.0"
.SH NAME
JUDO_MAXDEPTH \- maximum nesting depth
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.B #define JUDO_MAXDEPTH
.fi
.SH DESCRIPTION
The maximum number of nested compound structures that Judo can process.
This value can be set at configuration time.
Defining a maximum nesting depth ensures that malicious JSON cannot trigger a stack overflow.
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .