.TH "JUDO" "3" "Feb 18th 2025" "Judo 1.0.0-rc2"
.SH NAME
judo_numberify \- lexeme to float
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.BI "enum judo_result judo_numberify(const char *" lexeme ", int32_t " length ", judo_number *" number ");"
.fi
.SH DESCRIPTION
The \f[B]judo_numberify\f[R](3) function converts a lexeme of a JSON number into its floating-point representation.
The argument \f[I]lexeme\f[R] must point to a valid lexeme and \f[I]length\f[R] must be the lexeme’s length in UTF-8 code units.
The implementation writes the floating-point value to \f[I]number\f[R].
.SH RETURN VALUE
.TP
JUDO_SUCCESS
If the numeric value was written to \f[I]number\f[R].
.TP
JUDO_INVALID_OPERATION
If \f[C]stream\f[R], \f[C]string\f[R], or \f[I]number\f[R] are NULL.
.TP
JUDO_OUT_OF_RANGE
If the number cannot be represented by \f[B]judo_number\f[R](3).
.TP
JUDO_MALFUNCTION
If there is a defect in the implementation.
.SH SEE ALSO
.BR judo_number (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .