.TH "JUDO" "3" "Jul 31st 2025" "Judo 1.0.1"
.SH NAME
judo_span
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.B struct judo_span {
.RS
.B int32_t offset;
.B int32_t length;
.RE
.B };
.fi
.SH DESCRIPTION
The structure describes a range of UTF-8 code units.
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .