.TH "JUDO" "3" "Jul 31st 2025" "Judo 1.0.0"
.SH NAME
judo_type \- JSON value type
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.B enum judo_type {
.RS
.B JUDO_TYPE_INVALID,
.B JUDO_TYPE_NULL,
.B JUDO_TYPE_BOOL,
.B JUDO_TYPE_NUMBER,
.B JUDO_TYPE_STRING,
.B JUDO_TYPE_ARRAY,
.B JUDO_TYPE_OBJECT,
.RE
.B };
.fi
.SH DESCRIPTION
The type of a JSON value can be queried with the \f[B]judo_gettype\f[R](3) function.
.SH CONSTANTS
.TP
.BR JUDO_TYPE_INVALID
Not a valid type.
.TP
.BR JUDO_TYPE_NULL
Null type.
.TP
.BR JUDO_TYPE_BOOL
Boolean type.
.TP
.BR JUDO_TYPE_NUMBER
Number type.
.TP
.BR JUDO_TYPE_STRING
String type.
.TP
.BR JUDO_TYPE_ARRAY
Array type.
.TP
.BR JUDO_TYPE_OBJECT
Object type.
.SH SEE ALSO
.BR judo_value (3),
.BR judo_gettype (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .