.TH "JUDO" "3" "Sep 22nd 2025" "Judo 1.1.0"
.SH NAME
judo_gettype \- type of a JSON value
.SH LIBRARY
Embeddable JSON parser (libjudo, -ljudo)
.SH SYNOPSIS
.nf
.B #include <judo.h>
.PP
.BI "enum judo_type judo_gettype(const judo_value *" value ");"
.fi
.SH DESCRIPTION
The \f[B]judo_gettype\f[R](3) function returns the JSON type of \f[I]value\f[R].
If \f[I]value\f[R] is NULL, the implementation will return the constant \f[B]JUDO_TYPE_INVALID\f[R].
.SH RETURN VALUE
The JSON type of \f[I]value\f[R].
.SH SEE ALSO
.BR judo_type (3),
.BR judo_value (3)
.SH AUTHOR
.UR https://railgunlabs.com
Railgun Labs
.UE .
.SH INTERNET RESOURCES
The online documentation is
.UR https://railgunlabs.com/judo
published here
.UE .
.SH LICENSING
Judo is Free Software distributed under the GNU General Public License version 3 as published by the Free Software Foundation.
Alternatively, you can license the library under a proprietary license, as set out on the
.UR https://railgunlabs.com/judo/license/
Railgun Labs website
.UE .