blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://railgunlabs.com/judo/manual
    about: Review documentation and code examples.
  - name: 🔹 Basic Support
    url: https://railgunlabs.com/contribute
    about: Submit unsolicited bugs reports and code contributions.
  - name: 💎 Premium Support
    url: https://railgunlabs.com/services
    about: Priority support for bug reports and personal Q&A assistance.